# Generated by Django 3.2.4 on 2021-07-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(default=False, max_length=50)),
                ('movie_link', models.CharField(default=False, max_length=100)),
                ('details', models.CharField(default=False, max_length=200)),
            ],
            options={
                'db_table': 'films',
            },
        ),
    ]
