# Generated by Django 3.2.4 on 2021-07-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='details',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='films',
            name='movie_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='films',
            name='movie_name',
            field=models.CharField(max_length=50),
        ),
    ]
